version: '3.8'

services:
  neo4j:
    image: neo4j:5.14
    container_name: neo4j
    ports:
      - "7474:7474"  
      - "7687:7687"  
    environment:
      NEO4J_AUTH: neo4j/testpassword
      NEO4J_dbms_security_auth__minimum__password__length: 4
    volumes:
      - ./neo4j/data:/data
