basePath: /
host: localhost:8080
info:
  contact: {}
  description: Documentação da API que responde perguntas analíticas sobre COVID-19
    e vacinas
  title: API de Análise COVID-19
  version: "1.0"
paths: {}
swagger: "2.0"
